import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { getPokemonList, getPokemonDescription } from "../components/utils";
import React, { useState, useEffect } from "react";
import Card from "../components/Card";
import Select from "../components/Select"

// async function logData() {
//   const list = await getPokemonList();
//   console.log("list", list);

//   const description = await getPokemonDescription();
//   console.log("description", description);
// }
// logData();

/*
  Create drop down list - select pokemon from list
  Change displaying card to selected pokemon from list
  Display x data per card
  Create Previous and Next button
    Previous button is grayed out if it is not applicable
    Next button is grayed out if it it not applicable
*/

export default function Home() {
  const [pokemonList, setPokemonList] = useState([]);
  const [pokemonIndex, setPokemonIndex] = useState("1");

  useEffect(() => {
    async function getData() {
      const apiData = await getPokemonList();
      setPokemonList(apiData);
    }
    getData();
  }, []);

  const pokemonNames = pokemonList.map((pokemon, idx) => {
    return (
      <option key={idx} value={idx + 1}>
        {pokemon.name}
      </option>
    );
  });

  return (
    <div className={styles.container}>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Select
        pokemonNames={pokemonNames}
        onChange={e => setPokemonIndex(e.target.value)}
      >
      {pokemonNames}
      </Select>
      <Card pokemonIndex={pokemonIndex} pokemonNames={pokemonNames}/>
    </div>
  );
}
